import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Loader from "./components/Loader";
import Footer from "./components/Footer";
import Particles from "./components/Particles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ian Monsanto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Loader />
        <Header />
        {children}
        <Footer />
        <Particles
          className="absolute h-[400vh] inset-0 -z-10 animate-fade-in"
          quantity={300}
        />
      </body>
    </html>
  );
}
